version: '3.3'
services: 
    web:
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: php74
        depends_on: 
            - db
        volumes:
            - ./www:/var/www/html/
        ports: 
            - 80:80

    db:
        container_name: mysql8
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: alunno
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpassword
        volumes:
            - mysql-data:/var/lib/mysql
        ports: 
            - 3306:3306

    adminer:
        container_name: admin
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
        mysql-data:
